To Do list: List Structure
mmatongo/todo-list pull request #1
Opened 2021-08-16 11:16 UTC by mmatongo

### This pull request adds the following changes to the master branch of this repository.
- An `index.js` file that contains a simple array of tasks with three keys namely `description` `completed` `index`.
- A basic styles.css file that is loaded by webpack

2021-08-16 11:40 UTC, mikenath223 requested changes
Hello @mmatongo 👋

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-16 11:43 UTC, mikenath223 commented on src/styles.css
> +  display: inline-block;
- [ ] The project should look like the given design, kindly ensure it is a clone of the given design.

| Original | Yours |
| ----- | ------ |
| <img src='https://camo.githubusercontent.com/d04bee7a5b8f62cc6655dbec65c4d14583e4d78d0c434ddc070f6881bb9568fc/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f416355642d5f596a6a71672f302e6a7067' height='250px'> | <img src='https://user-images.githubusercontent.com/33323077/129558405-70639147-837d-4f09-b59e-4657f6dd7235.png' height='250px'> |

2021-08-17 13:16 UTC, vichuge requested changes
# Required Changes ♻️ ♻️ ⚠️ ⚠️ 🚦 🚦 

Hi dear student, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![star_wars_almost_there](https://user-images.githubusercontent.com/20563252/121369354-644f4900-c901-11eb-9844-50c85d0f206b.gif)


## Aspects to improve ♻️
_Check the comments under the review._

- [ ] Check the comments under the review. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-17 13:16 UTC, vichuge commented on package.json
> +  },
- [ ] I couldn't be able to run the project with `npm start`. Please, add the required to can do it. you can try adding `"start": "webpack serve --open"` after you'll need to install the webpack-dev-server plugin to continue. The same terminal helps you to install. 🐶

2021-08-17 13:22 UTC, mmatongo commented on package.json
> +  },
I'm confused, did I not meet all the project requirements?

2021-08-17 13:43 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-17 13:50 UTC, merged